### ISSUE TITLE
Fails trying to fetch a post that doesn't exist

### ISSUE THREAD

**Issue by lunasorcery** [cpsdqs/cohost-dl#1]
I'm guessing there's some inconsistency on cohost's end, maybe the post got deleted but the record of me liking it is still present or something? Any way to work around this would be great because it's stopping the downloader dead otherwise.

```
~~ loading post https://cohost.org/softwareangel/post/7146224-his-new-gig
GET https://cohost.org/softwareangel/post/7146224-his-new-gig
error: Uncaught (in promise) Error: {"status":404,"message":"Something went wrong."}
            throw new Error(await res.text());
                  ^
    at CohostContext.get (file:///Users/luna/code/external/cohost-dl/context.ts:58:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async CohostContext.getDocument (file:///Users/luna/code/external/cohost-dl/context.ts:199:28)
    at async loadPostPage (file:///Users/luna/code/external/cohost-dl/post-page.ts:98:22)
    at async file:///Users/luna/code/external/cohost-dl/main.ts:31:9
 ```

**Comment by c-probably-archived20260718** [comment]
These can now be skipped with SKIP_POSTS
