### ISSUE TITLE
script stops executing with error message + no out directory

### ISSUE THREAD

**Issue by Matytoonist** [cpsdqs/cohost-dl#15]
i left the script running overnight, and this morning i encountered this error:
```
error: Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    const trpcState = JSON.parse(
                           ^
    at JSON.parse (<anonymous>)
    at getPageState (file:///home/matias/Coding/cohost-dl/src/model.ts:253:28)
    at loadAllLikedPosts (file:///home/matias/Coding/cohost-dl/src/likes.ts:34:27)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async file:///home/matias/Coding/cohost-dl/main.ts:47:23
```

also the script hasnt created any new directory as far as i can see, so idk where is storing all of this besides the main.ts file it mentions

**Comment by c-probably-archived20260718** [comment]
You are probably not logged in. Is there no warning about it above? I can’t think of any other reason why that would happen…

The output directory is created right after this first stage succeeds, so that’s why you’re not seeing anything.

edit: wait, that’s not possible… maybe you have zero liked posts, or something? I’m not sure what the liked posts page (https://cohost.org/rc/liked-posts) looks like then. Maybe it looks completely different somehow

**Comment by Matytoonist** [comment]
i am logged in, and the liked posts page is definitely not empty. the last link it queried (https://cohost.org/rc/liked-posts?refTimestamp=1727317338866&skipPosts=3120) isnt empty either sooo

i have no idea what could be causing it, sorry :c

**Comment by Matytoonist** [comment]
okay i just tried again, this time removing the brackets around the username field ( ['matytoonist'] -> 'matytoonist' ) and it now seems to run fine

**Comment by c-probably-archived20260718** [comment]
you mean `export const PROJECTS = ['…']`? Removing those brackets has no effect on this and will just break it later.

Well, I am seeing absolutely no reason for that error to happen except if cohost.org somehow only sent half the page and died or something, so maybe you just had really bad luck…

**Comment by Matytoonist** [comment]
ok i just hit the same error as in the other open issue soo, i guess i'll wait x3
thanks for the help!

**Comment by c-probably-archived20260718** [comment]
wait you also have 100k likes? that’s scary. I thought I fixed that too though. oh well
