### ISSUE TITLE
Crashes with an apparent httpstatus 500, but cohost is still accessable

### ISSUE THREAD

**Issue by kyle-pegasus** [cpsdqs/cohost-dl#37]
As we know, cohost's backend is rotting and sometimes the site can go down for half an hour or so with error 500.

However, it turns out individual specific requests can experience this, even when the rest of the site is working.

For the past few hours I have suffered this:

`GET https://cohost.org/api/v1/trpc/login.loggedIn,projects.listEditedProjects?batch=1&input=%7B%7D
logged in as cuteboyhorse@gmail.com / @-pegasus
GET https://cohost.org/api/v1/trpc/posts.profilePosts?batch=1&input=%7B%220%22%3A%7B%22projectHandle%22%3A%22Pegasus-II%22%2C%22page%22%3A0%2C%22options%22%3A%7B%22hideAsks%22%3Afalse%2C%22hideReplies%22%3Afalse%2C%22hideShares%22%3Afalse%2C%22pinnedPostsAtTop%22%3Atrue%2C%22viewingOnProjectPage%22%3Atrue%7D%7D%7D
error: Uncaught (in promise) Error: [{"error":{"message":"","code":-32603,"data":{"code":"INTERNAL_SERVER_ERROR","httpStatus":500,"path":"posts.profilePosts"}}}]
            throw new Error(await res.text());
                  ^
    at CohostContext.get (file:///home/kyle/cohost-dl/src/context.ts:192:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async loadAllProjectPosts (file:///home/kyle/cohost-dl/src/project.ts:36:26)
    at async file:///home/kyle/cohost-dl/main.ts:99:27
`

I would appreciate a way to get around this and continue the scraping

**Comment by c-probably-archived20260718** [comment]
That appears to be a private page, so I think the error is that the account you’re using doesn’t have permission to view it. cohost outputs 500 in that case.
If you have an alt that *can* view this profile, I think you can switch to that alt in the web UI, copy the cookie from that tab (if it isn’t the same one already), and then run it again.

**Comment by kyle-pegasus** [comment]
The page it's trying to pull is my own alt page, which is the same account, with the same cookie. Switching to it in the browser seems to have cleared the error, but i could be mistaken.

**Comment by c-probably-archived20260718** [comment]
oh, in that case, to clarify: (1) switch to that page in the browser, and then (2) run cohost-dl again. It’s spooky action at a distance. Cohost API calls operate from the point of view of your browser’s currently active page
