### ISSUE TITLE
RollupError that becomes SyntaxError and breaks archiving

### ISSUE THREAD

**Issue by AmberSupremeDirt** [cpsdqs/cohost-dl#9]
ran into an error, i don't know what to make of it, doesn't seem to be fixed rerunning from scratch. included is the error that it becomes when attempting to rerun.

`GET https://cohost.org/static/a09d966cd188c9ebaa4c.png
GET https://cohost.org/static/edcc39b1702e4bd4b95e.svg
GET https://cohost.org/static/ca4719f7af550ea00632.png
error: Uncaught (in promise) RollupError: Could not resolve "./links/loggerLink.mjs" from "out/~src/3378dcdf/node_modules/.pnpm/@trpc+client@10.40.0_@trpc+server@10.40.0/node_modules/@trpc/client/dist/index.mjs"
    at getRollupError (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/rollup/4.21.2/dist/es/shared/parseAst.js:392:41)
    at error (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/rollup/4.21.2/dist/es/shared/parseAst.js:388:42)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/rollup/4.21.2/dist/es/shared/node-entry.js:19255:24)
    at file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/rollup/4.21.2/dist/es/shared/node-entry.js:19215:26
    at eventLoopTick (ext:core/01_core.js:175:7)
PS C:\Users\amber\Documents\cohost> deno run --allow-env --allow-ffi --allow-net --allow-read --allow-write=out main.ts
GET https://cohost.org/api/v1/trpc/login.loggedIn?batch=1&input=%7B%7D
logged in as amber@oneninefour.cl
~~ cohost source version 3378dcdf
compiling Javascript: project-index
error: Uncaught (in promise) SyntaxError: Error transforming out\static\edcc39b1702e4bd4b95e.svg: Unexpected token (2:2)
    at unexpected (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/sucrase/3.35.0/dist/parser/traverser/util.js:99:15)
    at nextJSXTagToken (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/sucrase/3.35.0/dist/parser/plugins/jsx/index.js:358:26)
    at jsxParseElement (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/sucrase/3.35.0/dist/parser/plugins/jsx/index.js:314:3)
    at parseExprAtom (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/sucrase/3.35.0/dist/parser/traverser/expression.js:455:28)
    at parseExprSubscripts (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/sucrase/3.35.0/dist/parser/traverser/expression.js:276:20)
    at parseMaybeUnary (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/sucrase/3.35.0/dist/parser/traverser/expression.js:257:20)
    at parseExprOps (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/sucrase/3.35.0/dist/parser/traverser/expression.js:185:20)
    at parseMaybeConditional (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/sucrase/3.35.0/dist/parser/traverser/expression.js:157:20)
    at baseParseMaybeAssign (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/sucrase/3.35.0/dist/parser/traverser/expression.js:142:20)
    at tsParseMaybeAssignWithJSX (file:///C:/Users/amber/AppData/Local/deno/npm/registry.npmjs.org/sucrase/3.35.0/dist/parser/plugins/typescript.js:1570:47)
PS C:\Users\amber\Documents\cohost>`

screenshot attached that's a little easier to look at
![Screenshot 2024-09-14 151440](https://github.com/user-attachments/assets/78afba7b-a996-45df-88e6-6af8c50febaa)

**Comment by c-probably-archived20260718** [comment]
ah… it is as I feared. ENABLE_JAVASCRIPT is broken on Windows. I don’t have a Windows device to test with at the moment, so I suppose you can turn that option off for now. I’ll be able to look at it next week, and then you can turn that option back on to add it to the download probably

**Comment by AmberSupremeDirt** [comment]
i ended up realizing that and just ran it on ubuntu where it worked fine, so yea.

**Comment by c-probably-archived20260718** [comment]
fixed in f10f2aa as far as I can test
